general:
    
    debug_level : "DEBUG"

    targets_file : "./targets/targets.json" 

    prng_seed : 0

    # Simulation time in seconds
    simulation_time : 100

    # Message rate in messages per second
    msg_rate : 10
    
    # Packet size in bytes
    min_packet_size : 2
    max_packet_size : 1024
    
